### ISSUE TITLE
Please provide context layers for the BEP

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#10]
MV and HV lines
We can take schools from OSM Extracts
We can take health from https://healthsites.io

**Comment by babakkhavari** [comment]
HV can be downlaoded from: https://energydata.info/dataset/transmission-grid-ecowas-region
MV can be downloaded from: https://energydata.info/dataset/distribution-grid-ecowas-region-west-africa/resource/51f5bae2-881f-49b5-b2c2-2221c3345f2a 

I agree regarding schools and health. Let us use the sources you suggest as the initial sources, the World Bank/SNV might have better data available to them.

**Comment by timlinux** [comment]
Thanks @babakkhavari 

For schools and health we will set up a live extract from OSM pending anything better (see #12 )

- [x] @seabilwe please take the HV and MV datasets from the links @babakkhavari provided above and publish them on GeoNode (along with tidy metadata etc) and then add them to the OSM Map, making sure that they are the most prominent feature shown on the map.
- [x] @meomancer Then make sure they are available in the BEP too please
