### ISSUE TITLE
Tweak geonode landing page

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#13]
![image](https://user-images.githubusercontent.com/178003/84982254-355b2880-b12e-11ea-9b01-63fe477f8e50.png)

Change the BEP in the top left corner to a home icon
Change the GEP in the menu to 'BEP' with tooltip 'Go to the Benin Electrification Platform'

**Comment by meomancer** [comment]
Done, but need cloudflare to refresh
