### ISSUE TITLE
Map panel theming

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#17]
The panels shoudl match the grayscale styling like this example:

![image](https://user-images.githubusercontent.com/178003/84983133-06de4d00-b130-11ea-961d-b1841d1dc909.png)

And only maps marked as 'featured' in their metadata should be listed on the home page

![image](https://user-images.githubusercontent.com/178003/84983169-1e1d3a80-b130-11ea-8da6-d495c07f2998.png)

See e.g. https://benin.gep.kartoza.com/maps/19/metadata_advanced

**Comment by meomancer** [comment]
it's done because using igrac theme
https://benin.gep.kartoza.com/
