### ISSUE TITLE
Set GeoNode to French

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#18]
I think there is a flag we can set to make french default - can you check and enable it please

**Comment by meomancer** [comment]
need this to be done first : https://github.com/kartoza/least-cost-electrification-benin/issues/19
because don't want to have 2 app with different language

**Comment by timlinux** [comment]
Agreed - can you figure out a process we can follow to get Faneva to translate it

**Comment by meomancer** [comment]
Now it's using French as default (although the translation on gep is not there yet)
