### ISSUE TITLE
BEP and GeoNode should default to French

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#19]
CC @babakkhavari 

I propose we ask @fanevajanuary to translate it all to French if possible.

@meomancer to help with deployment for BEP side

**Comment by meomancer** [comment]
BEP doesn't have framework for translation first
so we need to update the code to allow translation

**Comment by meomancer** [comment]
the transation frameworks already deployed
but we need translation on the gep side

here is the file 
https://github.com/kartoza/global-electrification-platform-explorer/blob/develop/app/assets/translations/fr.json

**Comment by meomancer** [comment]
Now it's using French as default (although the translation is not there yet)
