### ISSUE TITLE
Change Favicon

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#26]
![image](https://user-images.githubusercontent.com/178003/85330482-650e8580-b4cc-11ea-8e0e-a3877c4c9dff.png)

Can you make it a little wind turbine icon rather?

**Comment by meomancer** [comment]
![Selection_128](https://user-images.githubusercontent.com/4530905/85348945-383b8c00-b527-11ea-8129-0a48c529e797.png)

hi @timlinux 
the benin SDI favicon is same with gep already
could you do hard refresh?
