### ISSUE TITLE
Unable to upload video documents to GeoNode

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/least-cost-electrification-benin#37]
# Problem
I have some videos I need to upload as documents in the GeoNode and this produces

![error-upload](https://user-images.githubusercontent.com/2510900/88373690-94006b80-cd98-11ea-9bf9-d7bd4f57d5cf.png)

# Solution

Fix

**Comment by meomancer** [comment]
Fixed, can you retry @NyakudyaA ?

**Comment by NyakudyaA** [comment]
Thanks @meomancer
