### ISSUE TITLE
Publish distribution lines

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#44]
Distribution lines - clip to Benin probably not needed. Use gray and render beneath clusters. Split into two styles based on 'Situation' field. Existante and all others as solid gray line, En project as dashed gray line.

- [x] @timlinux add to GeoServer
- [x] @meomancer add to bep in legend box, above the clusters for now:

![bep-layers](https://user-images.githubusercontent.com/178003/92331091-dbeb0180-f06b-11ea-91a7-e66c7f729c2f.gif)

**Comment by timlinux** [comment]
OK distribution lines are available here:

https://benin.gep.kartoza.com/layers/geonode_data:geonode:benin_distribution_lines

![image](https://user-images.githubusercontent.com/178003/92333974-87eb1780-f081-11ea-832c-06b574528a69.png)

**Comment by meomancer** [comment]
Done
