### ISSUE TITLE
Publish transmission lines

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#45]
Transmission lines - clip to Benin - don't remove dodgy looking straight lines, add to BEP and GeoServer. Use black and render beneath clusters. Split into two styles based on 'Situation' field. Present solid black line, future as dashed black line.

- [x] @timlinux add to GeoNode
- [x] @meomancer add to bep in legend box, above the clusters for now:

![bep-layers](https://user-images.githubusercontent.com/178003/92331091-dbeb0180-f06b-11ea-91a7-e66c7f729c2f.gif)

**Comment by timlinux** [comment]
The clipped and styled lines are published here:

https://benin.gep.kartoza.com/layers/geonode_data:geonode:benin_transmission_lines_clipped

![image](https://user-images.githubusercontent.com/178003/92334102-d0ef9b80-f082-11ea-9771-e05b59bb0e12.png)


@meomancer please publish on the BEP

**Comment by meomancer** [comment]
Done
