### ISSUE TITLE
Publish PV Sites

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#46]
- [x] @timlinux add to GeoNode
- [x] @meomancer add to bep in legend box, above the clusters for now:

![bep-layers](https://user-images.githubusercontent.com/178003/92331091-dbeb0180-f06b-11ea-91a7-e66c7f729c2f.gif)

**Comment by timlinux** [comment]
Ok sites are published here:

https://benin.gep.kartoza.com/layers/geonode_data:geonode:benin_solar_sites

![image](https://user-images.githubusercontent.com/178003/92334036-18295c80-f082-11ea-95c5-5bb466693640.png)

@meomancer please publish in BEP

**Comment by meomancer** [comment]
Done
