### ISSUE TITLE
Republish schools and fix rendering and typo

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#47]
School from geoserver - not displaying  and fix name 'Schools' and huge red box on Ghana. First Tim to replace schools with new schools layer from Edouard

- [x] @timlinux add to GeoNode
- [x] @meomancer add to bep in legend box, above the clusters for now:

![bep-layers](https://user-images.githubusercontent.com/178003/92331091-dbeb0180-f06b-11ea-91a7-e66c7f729c2f.gif)

**Comment by timlinux** [comment]
@meomancer please used schools published here:


https://benin.gep.kartoza.com/layers/geonode_data:geonode:benin_education_sites

See 

https://github.com/kartoza/least-cost-electrification-benin/issues/40

**Comment by meomancer** [comment]
Done
