### ISSUE TITLE
BEP About page improvements

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-benin#5]
￼
![electrifynow energydata infoabout](https://user-images.githubusercontent.com/178003/84747507-429dd900-afaf-11ea-99ea-bd5457dce155.png)

Remove all text and only have:

WorldBank, KTH, Kartoza and SNV logos
Babak and Tim email address for contact

**Comment by meomancer** [comment]
fixed by https://github.com/kartoza/least-cost-electrification-benin/tree/develop
