### ISSUE TITLE
Administrative boundaries filters

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/least-cost-electrification-benin#58]
The administrative boundaries filters still crash when you remove one or more administrative boundaries.

**Comment by meomancer** [comment]
hi @babakkhavari 
what it is administrative boundary? is it "Departments"?

**Comment by babakkhavari** [comment]
Yes departments @meomancer

**Comment by meomancer** [comment]
that one i haven't updated the csv @babakkhavari , the files are too big and too much to be handle by my laptop
could you help me update it as per our disscussion why department does not working?
also could you also fix the "  id  " that has space?

**Comment by babakkhavari** [comment]
@meomancer Can you remind me again what the issue was with the admin? And send me a screenshot with the id problem?

**Comment by meomancer** [comment]
for department:
https://kartoza-snv-kth-benin.slack.com/archives/C014JA03LSU/p1599461955010200

![Selection_022](https://user-images.githubusercontent.com/4530905/93050641-6e535c80-f68d-11ea-9d9c-7c1958cff232.png)

for id, there is space after id
![Selection_023](https://user-images.githubusercontent.com/4530905/93050765-a78bcc80-f68d-11ea-8910-db1de41ea504.png)

**Comment by babakkhavari** [comment]
Ok, will let you know when fixed and uplaoded

**Comment by meomancer** [comment]
this is fixed, could you test it @babakkhavari ?

**Comment by babakkhavari** [comment]
Tested, works fine!
