### ISSUE TITLE
Metadata needed

### ISSUE THREAD

**Issue by seabilwe** [kartoza/least-cost-electrification-benin#64]
Hello @babakkhavari 

I may you please provide metadata details for the layers that have been uploaded to the clean cooking geonode instance, so that I may update the details for each of the layers.

![image](https://user-images.githubusercontent.com/56301949/114159813-7e32d680-9926-11eb-8fed-ea96240345c2.png)

**Comment by babakkhavari** [comment]
Hello @seabilwe, Ok me and Camilo will update these on the Geonode

**Comment by babakkhavari** [comment]
@seabilwe I will close this issue and we can continue the discussion in the clean cooking repository.
